"""The beekeeper's year: what to do when, as a timeline.

The dates are those of a reference region, central Germany (around Frankfurt). `app/season.py` moves
them earlier or later for the beekeeper's own place. They are guide values from the usual beekeeping
practice, not rules: the bloom and the weather decide, and anything about medicines is subject to the
approvals and the veterinary rules of the country. The texts say so where it matters, and the clients say
it once more under the timeline.

An entry has a start and an end ("MM-DD"); an end before the start means the entry runs over New Year.
`interval_days` marks something that is repeated during that time ("at least every 9 days").
`honey` ties an entry to a kind of honey (a forage key the moves already use), so a client can group by it.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

CATEGORIES = (
    "inspection", "swarm", "feeding", "varroa", "harvest", "migration", "bloom", "care", "winter",
)
LANGUAGES = ("en", "de", "fr", "es", "pl")


@dataclass(frozen=True)
class Entry:
    key: str
    category: str
    start: str  # "MM-DD" in the reference region
    end: str
    title: dict[str, str]
    body: dict[str, str]
    interval_days: Optional[int] = None
    honey: Optional[str] = None


def _t(en: str, de: str, fr: str, es: str, pl: str) -> dict[str, str]:
    return {"en": en, "de": de, "fr": fr, "es": es, "pl": pl}


ENTRIES: tuple[Entry, ...] = (
    # ── Winter ────────────────────────────────────────────────────────────────────────────
    Entry(
        "winter-rest", "winter", "01-01", "02-10",
        _t("Winter rest: leave the colonies alone",
           "Winterruhe: die Völker in Ruhe lassen",
           "Repos hivernal : laisser les colonies tranquilles",
           "Reposo invernal: dejar tranquilas las colonias",
           "Spoczynek zimowy: zostaw rodziny w spokoju"),
        _t("Do not open the hives. Keep the entrances free of snow and dead bees, listen at the wall (a quiet hum is good), and check the debris on the bottom board to see where the cluster sits and whether mites fall. Good time to melt wax, wire frames and repair equipment.",
           "Beuten nicht öffnen. Fluglöcher von Schnee und toten Bienen freihalten, an der Wand lauschen (leises Summen ist gut) und das Gemüll auf der Bodenfläche ansehen: Wo sitzt die Traube, fallen Milben? Gute Zeit, Wachs einzuschmelzen, Rähmchen zu drahten und Geräte zu reparieren.",
           "Ne pas ouvrir les ruches. Garder les entrées libres de neige et d’abeilles mortes, écouter contre la paroi (un léger bourdonnement est bon) et regarder les débris sur le plateau : où est la grappe, des varroas tombent-ils ? Bon moment pour fondre la cire, filer les cadres et réparer le matériel.",
           "No abrir las colmenas. Mantener las piqueras libres de nieve y de abejas muertas, escuchar en la pared (un zumbido suave es buena señal) y mirar los restos del fondo: ¿dónde está el racimo, caen varroas? Buen momento para fundir cera, alambrar cuadros y reparar el material.",
           "Nie otwieraj uli. Utrzymuj wyloty wolne od śniegu i martwych pszczół, nasłuchuj przy ściance (cichy szum to dobry znak) i obejrzyj osyp na dennicy: gdzie siedzi kłąb, czy spadają roztocza? To dobry czas na wytapianie wosku, druciowanie ramek i naprawę sprzętu."),
    ),
    Entry(
        "candy-feeding", "feeding", "02-01", "03-10",
        _t("Feed candy if the stores run low",
           "Mit Futterteig (Candy) füttern, wenn der Vorrat knapp wird",
           "Donner du candi si les provisions baissent",
           "Dar candy si las reservas escasean",
           "Podaj ciasto cukrowe, jeśli zapasy się kończą"),
        _t("Lift the hive at the back: a light colony needs help now, when brood starts and consumption rises. Put candy (feed dough) directly above the cluster, without opening the brood nest for long. Do not feed liquid syrup in the cold.",
           "Beute hinten anheben: Ein leichtes Volk braucht jetzt Hilfe, denn mit dem Brutbeginn steigt der Verbrauch. Futterteig (Candy) direkt über die Traube legen, ohne den Brutraum lange zu öffnen. Bei Kälte keinen flüssigen Sirup füttern.",
           "Soulever la ruche à l’arrière : une colonie légère a besoin d’aide maintenant, quand le couvain démarre et que la consommation monte. Poser du candi (pâte de nourrissement) juste au-dessus de la grappe, sans laisser la ruche ouverte longtemps. Pas de sirop liquide par temps froid.",
           "Levantar la colmena por detrás: una colonia ligera necesita ayuda ahora, cuando empieza la cría y sube el consumo. Poner candy (pasta de alimentación) justo encima del racimo, sin dejar abierta la cría mucho tiempo. No dar jarabe líquido con frío.",
           "Unieś ul z tyłu: lekka rodzina potrzebuje teraz pomocy, bo z początkiem czerwienia rośnie zużycie pokarmu. Połóż ciasto cukrowe (candy) bezpośrednio nad kłębem, nie otwierając gniazda na długo. Na mrozie nie podawaj płynnego syropu."),
    ),
    Entry(
        "cleansing-flight", "care", "02-15", "03-20",
        _t("First cleansing flight",
           "Erster Reinigungsflug",
           "Premier vol de propreté",
           "Primer vuelo de limpieza",
           "Pierwszy oblot oczyszczający"),
        _t("On the first mild day (about 10 °C or more) the bees fly to empty themselves. Do not disturb them. Afterwards clear dead bees from the entrance and the bottom board, check the mouse guard and look at the hive from outside: wet walls and yellow spots point to problems.",
           "Am ersten milden Tag (etwa 10 °C oder mehr) fliegen die Bienen aus, um sich zu entleeren. Nicht stören. Danach tote Bienen aus dem Flugloch und von der Bodenfläche räumen, das Mäusegitter prüfen und die Beute von außen ansehen: Nasse Wände und gelbe Flecken deuten auf Probleme hin.",
           "Le premier jour doux (environ 10 °C ou plus), les abeilles sortent se vider. Ne pas les déranger. Ensuite, retirer les abeilles mortes de l’entrée et du plateau, vérifier la grille anti-souris et regarder la ruche de l’extérieur : parois mouillées et taches jaunes signalent des problèmes.",
           "El primer día templado (unos 10 °C o más) las abejas salen a vaciarse. No molestarlas. Después, retirar las abejas muertas de la piquera y del fondo, comprobar la rejilla contra ratones y mirar la colmena por fuera: paredes mojadas y manchas amarillas indican problemas.",
           "W pierwszy łagodny dzień (około 10 °C lub więcej) pszczoły wylatują, żeby się oczyścić. Nie przeszkadzaj im. Potem usuń martwe pszczoły sprzed wylotu i z dennicy, sprawdź zabezpieczenie przed myszami i obejrzyj ul z zewnątrz: mokre ścianki i żółte plamy wskazują na kłopoty."),
    ),
    # ── Spring ────────────────────────────────────────────────────────────────────────────
    Entry(
        "first-inspection", "inspection", "03-10", "04-10",
        _t("Start of the inspections",
           "Beginn der Kontrollen",
           "Début des visites",
           "Comienzo de las revisiones",
           "Początek przeglądów"),
        _t("On the first calm day above 12–15 °C do a quick first inspection: is there a queen (eggs, young larvae), a compact brood pattern, enough stores, enough room? Replace a dead or drone-laying queen early. Replace old, dark combs gradually.",
           "Am ersten ruhigen Tag über 12–15 °C eine zügige erste Kontrolle: Ist eine Königin da (Eier, junge Larven), ist das Brutnest geschlossen, reicht der Futtervorrat, ist genug Platz? Eine tote oder drohnenbrütige Königin früh ersetzen. Alte, dunkle Waben nach und nach erneuern.",
           "Le premier jour calme au-dessus de 12–15 °C, faire une première visite rapide : y a-t-il une reine (œufs, jeunes larves), un couvain compact, assez de provisions, assez de place ? Remplacer tôt une reine morte ou bourdonneuse. Renouveler peu à peu les vieux rayons foncés.",
           "El primer día tranquilo por encima de 12–15 °C, hacer una primera revisión rápida: ¿hay reina (huevos, larvas jóvenes), una cría compacta, reservas suficientes, espacio suficiente? Sustituir pronto una reina muerta o zanganera. Renovar poco a poco los panales viejos y oscuros.",
           "W pierwszy spokojny dzień powyżej 12–15 °C zrób szybki pierwszy przegląd: czy jest matka (jaja, młode larwy), zwarty czerw, dość zapasów i miejsca? Martwą lub trutowiejącą matkę wymień wcześnie. Stare, ciemne plastry wymieniaj stopniowo."),
    ),
    Entry(
        "foulbrood-check", "care", "03-10", "04-30",
        _t("Check for foulbrood",
           "Auf Faulbrut achten",
           "Surveiller la loque",
           "Vigilar la loque",
           "Sprawdź, czy nie ma zgnilca"),
        _t("While inspecting, look at the brood: sunken, perforated cappings, a patchy pattern or a ropy, brown mass in the cell (match test) are warning signs. Where it is required or recommended, send a feed ring sample to the lab. Suspicion must be reported to the veterinary authority.",
           "Bei der Kontrolle die Brut ansehen: eingefallene, durchlöcherte Zelldeckel, ein lückiges Brutbild oder ein fadenziehender brauner Brei in der Zelle (Streichholzprobe) sind Warnzeichen. Wo vorgeschrieben oder empfohlen, eine Futterkranzprobe ins Labor schicken. Ein Verdacht muss dem Veterinäramt gemeldet werden.",
           "Pendant la visite, regarder le couvain : opercules affaissés et percés, couvain lacunaire ou masse brune filante dans l’alvéole (test de l’allumette) sont des signes d’alerte. Là où c’est exigé ou conseillé, envoyer un échantillon de couronne de miel au laboratoire. Un soupçon doit être déclaré à l’autorité vétérinaire.",
           "Al revisar, mirar la cría: opérculos hundidos y perforados, cría salteada o una masa marrón que hace hilo en la celda (prueba de la cerilla) son señales de alarma. Donde sea obligatorio o recomendable, enviar una muestra de miel de la corona al laboratorio. Una sospecha debe comunicarse a la autoridad veterinaria.",
           "Podczas przeglądu oglądaj czerw: zapadnięte, dziurkowane zasklepy, pstry czerw albo ciągliwa brązowa masa w komórce (próba zapałką) to sygnały ostrzegawcze. Tam, gdzie jest to wymagane lub zalecane, wyślij próbkę do laboratorium. Podejrzenie trzeba zgłosić organowi weterynaryjnemu."),
    ),
    Entry(
        "spring-bloom", "bloom", "03-15", "05-10",
        _t("Early bloom: hazel, willow, dandelion, fruit trees",
           "Frühtracht: Hasel, Weide, Löwenzahn, Obstbäume",
           "Floraison précoce : noisetier, saule, pissenlit, arbres fruitiers",
           "Floración temprana: avellano, sauce, diente de león, frutales",
           "Wczesne kwitnienie: leszczyna, wierzba, mniszek, drzewa owocowe"),
        _t("Pollen and nectar make the colony grow quickly. Keep stores in the brood nest, widen the nest only when the combs are well covered with bees, and keep an eye on spraying in the orchards nearby. A late frost can stop the build-up.",
           "Pollen und Nektar lassen das Volk schnell wachsen. Futter im Brutnest lassen, das Nest nur erweitern, wenn die Waben gut mit Bienen besetzt sind, und Spritzungen in nahen Obstanlagen im Auge behalten. Ein später Frost kann den Aufbau bremsen.",
           "Le pollen et le nectar font grandir vite la colonie. Laisser des provisions dans le nid à couvain, n’agrandir le nid que lorsque les rayons sont bien couverts d’abeilles, et surveiller les traitements des vergers voisins. Un gel tardif peut freiner le développement.",
           "El polen y el néctar hacen crecer rápido la colonia. Dejar reservas en el nido de cría, ampliar el nido solo cuando los panales estén bien cubiertos de abejas y vigilar los tratamientos de los frutales cercanos. Una helada tardía puede frenar el desarrollo.",
           "Pyłek i nektar sprawiają, że rodzina szybko się rozwija. Trzymaj zapasy w gnieździe, rozszerzaj gniazdo dopiero wtedy, gdy plastry są dobrze obsiadłe, i miej na oku opryski w pobliskich sadach. Późny przymrozek może zatrzymać rozwój."),
    ),
    Entry(
        "comb-renewal", "care", "04-01", "05-15",
        _t("Renew combs: foundation frames",
           "Waben erneuern: Mittelwände einhängen",
           "Renouveler les rayons : cadres de cire gaufrée",
           "Renovar panales: cuadros con cera estampada",
           "Wymiana plastrów: ramki z węzą"),
        _t("Hang foundation frames next to the brood nest so the bees draw fresh comb. About a third of the combs per year keeps the colony healthy; old combs collect pathogens and residues. Remove the oldest combs at the edge.",
           "Mittelwände neben das Brutnest hängen, damit die Bienen frische Waben bauen. Etwa ein Drittel der Waben pro Jahr zu erneuern hält das Volk gesund; alte Waben sammeln Erreger und Rückstände. Die ältesten Waben am Rand entnehmen.",
           "Placer des cadres de cire gaufrée à côté du nid à couvain pour que les abeilles bâtissent des rayons neufs. Renouveler environ un tiers des rayons par an garde la colonie saine ; les vieux rayons accumulent agents pathogènes et résidus. Retirer les plus vieux rayons en bordure.",
           "Colgar cuadros con cera estampada junto al nido de cría para que las abejas estiren panal nuevo. Renovar un tercio de los panales al año mantiene sana la colonia; los panales viejos acumulan patógenos y residuos. Retirar los más viejos del borde.",
           "Powieś ramki z węzą obok gniazda czerwiowego, żeby pszczoły zbudowały świeże plastry. Wymiana około jednej trzeciej plastrów rocznie utrzymuje rodzinę w zdrowiu; stare plastry gromadzą patogeny i pozostałości. Najstarsze plastry z brzegu usuwaj."),
    ),
    Entry(
        "drone-frame-insert", "varroa", "04-10", "05-05",
        _t("Hang a drone frame",
           "Drohnenrahmen einhängen",
           "Poser un cadre à mâles",
           "Colgar un cuadro de zánganos",
           "Powieś ramkę trutową"),
        _t("Hang a drone frame (a frame with wide cells or a frame with a strip of foundation) at the edge of the brood nest. Varroa mites prefer drone brood, so cutting it out removes many of them without chemicals. Plan to cut it out when it is capped.",
           "Einen Drohnenrahmen (Rahmen mit weiten Zellen oder mit einem Streifen Mittelwand) am Rand des Brutnests einhängen. Varroamilben bevorzugen Drohnenbrut; wird sie ausgeschnitten, nimmt man viele Milben ohne Chemie heraus. Das Ausschneiden einplanen, sobald die Brut verdeckelt ist.",
           "Poser un cadre à mâles (cadre à grandes alvéoles ou avec une bande de cire gaufrée) en bordure du nid à couvain. Les varroas préfèrent le couvain de mâles ; le découper retire beaucoup d’acariens sans produit chimique. Prévoir de le découper une fois operculé.",
           "Colgar un cuadro de zánganos (cuadro con celdas anchas o con una tira de cera) en el borde del nido de cría. Las varroas prefieren la cría de zángano; al cortarla se quitan muchos ácaros sin química. Planear cortarla cuando esté operculada.",
           "Powieś ramkę trutową (ramkę z szerokimi komórkami albo z paskiem węzy) na skraju gniazda czerwiowego. Roztocza Varroa wolą czerw trutowy, więc jego wycięcie usuwa ich wiele bez chemii. Zaplanuj wycięcie, gdy czerw zostanie zasklepiony."),
    ),
    Entry(
        "honey-super", "care", "04-15", "05-10",
        _t("Put the honey supers on",
           "Honigräume aufsetzen",
           "Poser les hausses",
           "Poner las alzas",
           "Załóż nadstawki miodowe"),
        _t("Before the rape blooms put on the honey super (queen excluder below) once the brood chamber is full of bees. Waiting too long makes the colony crowded and pushes it towards swarming. Give a second super when the first is two thirds filled.",
           "Vor der Rapsblüte den Honigraum aufsetzen (Absperrgitter darunter), sobald der Brutraum voller Bienen ist. Zu langes Warten macht das Volk eng und treibt es zum Schwärmen. Einen zweiten Honigraum geben, wenn der erste zu zwei Dritteln gefüllt ist.",
           "Avant la floraison du colza, poser la hausse (grille à reine dessous) dès que le corps est plein d’abeilles. Attendre trop longtemps entasse la colonie et la pousse à essaimer. Donner une seconde hausse quand la première est remplie aux deux tiers.",
           "Antes de la floración de la colza, poner el alza (excluidor debajo) cuando la cámara de cría esté llena de abejas. Esperar demasiado aprieta la colonia y la empuja a enjambrar. Dar una segunda alza cuando la primera esté llena a dos tercios.",
           "Przed kwitnieniem rzepaku załóż nadstawkę (krata odgrodowa pod spodem), gdy korpus jest pełen pszczół. Zbyt długie czekanie ścieśnia rodzinę i popycha ją do rojenia. Drugą nadstawkę daj, gdy pierwsza jest wypełniona w dwóch trzecich."),
    ),
    Entry(
        "swarm-control", "swarm", "04-20", "06-30",
        _t("Swarm control: look for queen cells",
           "Schwarmkontrolle: auf Weiselzellen achten",
           "Contrôle de l’essaimage : chercher les cellules royales",
           "Control de la enjambrazón: buscar celdas reales",
           "Kontrola rójki: szukaj mateczników"),
        _t("In the swarming season check every colony weekly, and at the latest every 9 days: a capped queen cell means the old queen leaves soon. Look at the edges and bottoms of the frames. Break out play cups only if they are empty; with real queen cells make a nucleus or an artificial swarm instead of just breaking them, and give room.",
           "In der Schwarmzeit jedes Volk wöchentlich kontrollieren, spätestens alle 9 Tage: Eine verdeckelte Weiselzelle bedeutet, dass die alte Königin bald ausfliegt. Ränder und Unterseiten der Waben ansehen. Leere Spielnäpfchen können bleiben; bei echten Weiselzellen besser einen Ableger oder Kunstschwarm bilden, als sie nur auszubrechen, und Platz geben.",
           "En période d’essaimage, visiter chaque colonie chaque semaine, au plus tard tous les 9 jours : une cellule royale operculée annonce le départ proche de la vieille reine. Regarder les bords et le dessous des cadres. Les godets vides peuvent rester ; avec de vraies cellules royales, faire un essaim artificiel ou un nucléus plutôt que de seulement les détruire, et donner de la place.",
           "En la época de enjambrazón, revisar cada colonia cada semana y como máximo cada 9 días: una celda real operculada significa que la reina vieja saldrá pronto. Mirar los bordes y la parte inferior de los cuadros. Las tazas vacías pueden quedarse; con celdas reales de verdad, mejor hacer un núcleo o un enjambre artificial que solo romperlas, y dar espacio.",
           "W sezonie rojowym sprawdzaj każdą rodzinę co tydzień, najpóźniej co 9 dni: zasklepiony matecznik oznacza, że stara matka wkrótce odleci. Oglądaj brzegi i dolne części ramek. Miseczki matecznikowe wyłamuj tylko wtedy, gdy są puste; przy prawdziwych mateczkach zrób odkład lub rój sztuczny zamiast je tylko wyłamywać i daj miejsce."),
        interval_days=9,
    ),
    Entry(
        "migrate-rapeseed", "migration", "04-15", "05-05",
        _t("Rapeseed: move the hives to the field",
           "Raps: Völker zum Rapsfeld wandern",
           "Colza : emmener les ruches au champ",
           "Colza: llevar las colmenas al campo",
           "Rzepak: przewieź ule na pole"),
        _t("Move at the start of the bloom, at night or very early, with the honey supers on and enough space. Rapeseed gives a fast, heavy flow for about three weeks; ask the farmer about spraying first. Check the colonies are strong and the combs are drawn.",
           "Zu Blühbeginn wandern, nachts oder sehr früh, mit aufgesetzten Honigräumen und genug Platz. Raps liefert etwa drei Wochen eine schnelle, starke Tracht; vorher beim Landwirt nach Spritzungen fragen. Prüfen, dass die Völker stark und die Waben ausgebaut sind.",
           "Déplacer au début de la floraison, de nuit ou très tôt, avec les hausses posées et assez de place. Le colza donne pendant environ trois semaines une miellée rapide et forte ; demander d’abord à l’agriculteur s’il traite. Vérifier que les colonies sont fortes et les rayons bâtis.",
           "Trasladar al comienzo de la floración, de noche o muy temprano, con las alzas puestas y espacio suficiente. La colza da durante unas tres semanas un flujo rápido y fuerte; preguntar antes al agricultor por los tratamientos. Comprobar que las colonias son fuertes y los panales están estirados.",
           "Przewoź na początku kwitnienia, nocą lub bardzo wcześnie rano, z nadstawkami i dużym zapasem miejsca. Rzepak daje szybki, obfity pożytek przez około trzy tygodnie; najpierw zapytaj rolnika o opryski. Sprawdź, czy rodziny są silne i plastry odbudowane."),
        honey="rapeseed",
    ),
    Entry(
        "drone-brood-cutting", "varroa", "05-10", "07-10",
        _t("Cut out the capped drone brood",
           "Verdeckelte Drohnenbrut ausschneiden",
           "Découper le couvain de mâles operculé",
           "Cortar la cría de zángano operculada",
           "Wytnij zasklepiony czerw trutowy"),
        _t("Drone brood is capped for about 10 days and the drones hatch after 24; cut the capped brood out about every three weeks, before they hatch, and put the frame back. Three or four cuts until early July take a good share of the mites with them. Freeze or melt the brood; do not leave it lying around.",
           "Drohnenbrut ist etwa 10 Tage verdeckelt und die Drohnen schlüpfen nach 24 Tagen; die verdeckelte Brut etwa alle drei Wochen vor dem Schlupf ausschneiden und den Rahmen zurückhängen. Drei bis vier Schnitte bis Anfang Juli nehmen einen guten Teil der Milben mit. Die Brut einfrieren oder einschmelzen und nicht liegen lassen.",
           "Le couvain de mâles est operculé environ 10 jours et les mâles naissent après 24 jours ; découper le couvain operculé environ toutes les trois semaines, avant la naissance, et remettre le cadre. Trois ou quatre coupes jusqu’à début juillet emportent une bonne part des acariens. Congeler ou fondre le couvain, ne pas le laisser traîner.",
           "La cría de zángano está operculada unos 10 días y los zánganos nacen a los 24; cortar la cría operculada más o menos cada tres semanas, antes de que nazcan, y volver a colgar el cuadro. Tres o cuatro cortes hasta principios de julio se llevan una buena parte de los ácaros. Congelar o fundir la cría; no dejarla tirada.",
           "Czerw trutowy jest zasklepiony około 10 dni, a trutnie wygryzają się po 24; wycinaj zasklepiony czerw mniej więcej co trzy tygodnie, zanim się wygryzą, i wstawiaj ramkę z powrotem. Trzy lub cztery cięcia do początku lipca usuwają dużą część roztoczy. Czerw zamroź lub wytop; nie zostawiaj go na wierzchu."),
        interval_days=21,
    ),
    Entry(
        "harvest-rapeseed", "harvest", "05-15", "06-05",
        _t("Rapeseed honey: extract at once",
           "Rapshonig: sofort schleudern",
           "Miel de colza : extraire tout de suite",
           "Miel de colza: extraer enseguida",
           "Miód rzepakowy: odwiruj od razu"),
        _t("Rapeseed honey sets hard within days. Take the supers off as soon as the bloom ends and the combs are at least two thirds capped (shake test: nothing sprays out), and extract at once while the honey is warm. Over 18 % water, stir it later to a fine cream instead.",
           "Rapshonig wird innerhalb weniger Tage fest. Honigräume abnehmen, sobald die Blüte vorbei und die Waben zu mindestens zwei Dritteln verdeckelt sind (Schüttelprobe: nichts spritzt heraus), und sofort schleudern, solange der Honig warm ist. Bei über 18 % Wasser später zu feiner Creme rühren.",
           "Le miel de colza durcit en quelques jours. Retirer les hausses dès que la floraison est finie et que les rayons sont operculés aux deux tiers au moins (test de secouage : rien ne gicle), et extraire aussitôt tant que le miel est chaud. Au-dessus de 18 % d’eau, le travailler plus tard en crème fine.",
           "La miel de colza se solidifica en pocos días. Quitar las alzas en cuanto acabe la floración y los panales estén operculados al menos a dos tercios (prueba de sacudida: no salta nada) y extraer enseguida, mientras la miel está caliente. Con más de 18 % de agua, cremarla después.",
           "Miód rzepakowy krystalizuje w ciągu kilku dni. Zdejmij nadstawki zaraz po końcu kwitnienia, gdy plastry są zasklepione co najmniej w dwóch trzecich (próba strząsania: nic nie pryska), i odwiruj od razu, póki miód jest ciepły. Przy zawartości wody powyżej 18 % lepiej potem zamieszać go na kremowy."),
        honey="rapeseed",
    ),
    Entry(
        "migrate-acacia", "migration", "05-10", "05-30",
        _t("Black locust (acacia): short bloom, move on time",
           "Robinie (Akazie): kurze Blüte, rechtzeitig wandern",
           "Robinier (acacia) : floraison courte, déplacer à temps",
           "Robinia (acacia): floración corta, trasladar a tiempo",
           "Robinia akacjowa: krótkie kwitnienie, przewieź na czas"),
        _t("The locust blooms only about ten days, and the weather decides whether it yields. Move when the first flowers open, with strong colonies and an empty super ready. Do not mix it with other flows if you want a pure acacia honey.",
           "Die Robinie blüht nur etwa zehn Tage, und das Wetter entscheidet, ob sie honigt. Wandern, wenn die ersten Blüten aufgehen, mit starken Völkern und einem leeren Honigraum bereit. Nicht mit anderen Trachten mischen, wenn es reiner Akazienhonig werden soll.",
           "Le robinier ne fleurit qu’une dizaine de jours, et la météo décide s’il donne. Déplacer à l’ouverture des premières fleurs, avec des colonies fortes et une hausse vide prête. Ne pas mélanger avec d’autres miellées pour un miel d’acacia pur.",
           "La robinia florece solo unos diez días y el tiempo decide si da miel. Trasladar cuando se abran las primeras flores, con colonias fuertes y un alza vacía lista. No mezclar con otras floraciones si se quiere una miel de acacia pura.",
           "Robinia kwitnie tylko około dziesięciu dni, a o wydajności decyduje pogoda. Przewieź, gdy otworzą się pierwsze kwiaty, z silnymi rodzinami i pustą nadstawką w gotowości. Nie mieszaj z innymi pożytkami, jeśli chcesz uzyskać czysty miód akacjowy."),
        honey="acacia",
    ),
    Entry(
        "harvest-acacia", "harvest", "05-28", "06-15",
        _t("Acacia honey: extract when capped",
           "Akazienhonig: bei Verdeckelung schleudern",
           "Miel d’acacia : extraire quand c’est operculé",
           "Miel de acacia: extraer cuando esté operculada",
           "Miód akacjowy: odwiruj po zasklepieniu"),
        _t("Acacia honey stays liquid for a long time and is clear. Harvest when the combs are well capped and before the next flow mixes in (linden, honeydew). Keep the supers of different flows apart so the acacia stays pure.",
           "Akazienhonig bleibt lange flüssig und ist hell. Ernten, wenn die Waben gut verdeckelt sind und bevor die nächste Tracht (Linde, Honigtau) sich daruntermischt. Honigräume verschiedener Trachten getrennt halten, damit der Akazienhonig sortenrein bleibt.",
           "Le miel d’acacia reste longtemps liquide et clair. Récolter quand les rayons sont bien operculés et avant que la miellée suivante (tilleul, miellat) ne s’y mêle. Garder séparées les hausses des différentes miellées pour que l’acacia reste pur.",
           "La miel de acacia permanece líquida mucho tiempo y es clara. Cosechar cuando los panales estén bien operculados y antes de que se mezcle la floración siguiente (tilo, mielada). Mantener separadas las alzas de cada floración para que la acacia siga pura.",
           "Miód akacjowy długo pozostaje płynny i jest przejrzysty. Zbieraj, gdy plastry są dobrze zasklepione i zanim zmiesza się z następnym pożytkiem (lipa, spadź). Nadstawki z różnych pożytków trzymaj osobno, żeby akacja pozostała czysta."),
        honey="acacia",
    ),
    Entry(
        "replace-queens", "care", "06-15", "08-15",
        _t("Requeen and make nuclei",
           "Umweiseln und Ableger bilden",
           "Remplacer les reines et faire des nucléus",
           "Cambiar reinas y hacer núcleos",
           "Wymień matki i zrób odkłady"),
        _t("Queens older than two years lay less well and swarm more. After the main flow replace weak or old queens with a young, mated queen, and keep a few nuclei as a reserve for the winter losses.",
           "Königinnen über zwei Jahren legen schlechter und schwärmen eher. Nach der Haupttracht schwache oder alte Königinnen durch eine junge, begattete Königin ersetzen und einige Ableger als Reserve für Winterverluste halten.",
           "Les reines de plus de deux ans pondent moins bien et essaiment davantage. Après la miellée principale, remplacer les reines faibles ou vieilles par une jeune reine fécondée, et garder quelques nucléus en réserve pour les pertes d’hiver.",
           "Las reinas de más de dos años ponen peor y enjambran más. Tras la floración principal, cambiar las reinas débiles o viejas por una reina joven fecundada, y guardar algunos núcleos de reserva para las pérdidas de invierno.",
           "Matki starsze niż dwa lata słabiej czerwią i częściej się rójkują. Po głównym pożytku wymień słabe lub stare matki na młode, unasiennione i miej kilka odkładów w rezerwie na straty zimowe."),
    ),
    Entry(
        "migrate-chestnut", "migration", "06-10", "07-10",
        _t("Sweet chestnut: move south of the Alps and in mild regions",
           "Edelkastanie: in den Süden und in milde Regionen wandern",
           "Châtaignier : emmener les ruches dans le sud et les régions douces",
           "Castaño: trasladar al sur y a regiones suaves",
           "Kasztan jadalny: przewieź na południe od Alp i w łagodne regiony"),
        _t("Chestnut blooms in late June and July in the south and in mild valleys. The honey is dark and bitter-spicy, and it stays liquid. Move with empty supers and plenty of water for the colony.",
           "Die Kastanie blüht Ende Juni und im Juli im Süden und in milden Tälern. Der Honig ist dunkel, herb-würzig und bleibt flüssig. Mit leeren Honigräumen und genug Wasser für das Volk wandern.",
           "Le châtaignier fleurit fin juin et en juillet dans le sud et les vallées douces. Le miel est foncé, légèrement amer et épicé, et reste liquide. Déplacer avec des hausses vides et assez d’eau pour la colonie.",
           "El castaño florece a finales de junio y en julio en el sur y en valles suaves. La miel es oscura, amarga y especiada, y permanece líquida. Trasladar con alzas vacías y agua suficiente para la colonia.",
           "Kasztan kwitnie pod koniec czerwca i w lipcu na południu i w łagodnych dolinach. Miód jest ciemny, gorzkawo-korzenny i pozostaje płynny. Przewoź z pustymi nadstawkami i dużą ilością wody dla rodziny."),
        honey="chestnut",
    ),
    Entry(
        "migrate-linden", "migration", "06-15", "07-10",
        _t("Linden: move to the linden trees",
           "Linde: zu den Lindenbäumen wandern",
           "Tilleul : emmener les ruches aux tilleuls",
           "Tilo: trasladar a los tilos",
           "Lipa: przewieź do lip"),
        _t("Linden blooms from about the end of June for two to three weeks, especially in towns and parks. Put empty supers on before you move; a strong flow comes fast on warm, humid days.",
           "Die Linde blüht etwa ab Ende Juni zwei bis drei Wochen lang, vor allem in Städten und Parks. Vor dem Wandern leere Honigräume aufsetzen; an warmen, schwülen Tagen kommt die Tracht schnell und stark.",
           "Le tilleul fleurit à partir de fin juin pendant deux à trois semaines, surtout en ville et dans les parcs. Poser des hausses vides avant de déplacer ; la miellée est rapide et forte les jours chauds et lourds.",
           "El tilo florece desde finales de junio durante dos o tres semanas, sobre todo en ciudades y parques. Poner alzas vacías antes de trasladar; el flujo llega rápido y fuerte en días cálidos y bochornosos.",
           "Lipa kwitnie od końca czerwca przez dwa do trzech tygodni, zwłaszcza w miastach i parkach. Załóż puste nadstawki przed przewozem; silny pożytek przychodzi szybko w ciepłe, wilgotne dni."),
        honey="linden",
    ),
    Entry(
        "migrate-fir", "migration", "06-01", "07-31",
        _t("Forest honeydew: fir and spruce",
           "Waldtracht: Tanne und Fichte",
           "Miellat de forêt : sapin et épicéa",
           "Mielada de bosque: abeto y picea",
           "Spadź leśna: jodła i świerk"),
        _t("Whether the forest yields depends on the honeydew insects, which you can see as shiny drops on the needles and ants running up the trunk. Move only when the flow is confirmed, with room and a strong colony. Take the honey out in time: honeydew honey can set in the comb.",
           "Ob der Wald honigt, hängt von den Honigtau-Insekten ab, erkennbar an glänzenden Tropfen auf den Nadeln und Ameisen am Stamm. Nur wandern, wenn die Tracht bestätigt ist, mit Platz und einem starken Volk. Den Honig rechtzeitig ernten: Honigtauhonig kann in der Wabe erstarren.",
           "Que la forêt donne dépend des insectes à miellat, visibles aux gouttes brillantes sur les aiguilles et aux fourmis sur le tronc. Ne déplacer que si la miellée est confirmée, avec de la place et une colonie forte. Récolter à temps : le miel de miellat peut se figer dans le rayon.",
           "Que el bosque dé miel depende de los insectos de la mielada, que se ven como gotas brillantes en las agujas y hormigas en el tronco. Trasladar solo cuando el flujo esté confirmado, con espacio y una colonia fuerte. Cosechar a tiempo: la miel de mielada puede cristalizar en el panal.",
           "To, czy las daje miód, zależy od owadów produkujących spadź; widać je jako błyszczące krople na igłach i mrówki biegnące po pniu. Przewoź dopiero po potwierdzeniu pożytku, z miejscem i silną rodziną. Miód zbierz na czas: spadź może skrystalizować w plastrach."),
        honey="fir",
    ),
    Entry(
        "migrate-lavender", "migration", "06-15", "07-31",
        _t("Lavender: move to the south of France and Spain",
           "Lavendel: nach Südfrankreich und Spanien wandern",
           "Lavande : emmener les ruches en Provence et en Espagne",
           "Lavanda: trasladar al sur de Francia y a España",
           "Lawenda: przewieź na południe Francji i do Hiszpanii"),
        _t("Lavender blooms from mid-June to the end of July, depending on the altitude. Move at night in the cool, give shade and water, and expect a pale, fragrant honey that sets fine.",
           "Lavendel blüht je nach Höhenlage von Mitte Juni bis Ende Juli. Nachts in der Kühle wandern, Schatten und Wasser geben; der Honig ist hell, aromatisch und kristallisiert fein.",
           "La lavande fleurit de mi-juin à fin juillet selon l’altitude. Déplacer de nuit, au frais, donner ombre et eau ; le miel est clair, parfumé et cristallise finement.",
           "La lavanda florece de mediados de junio a finales de julio según la altitud. Trasladar de noche, con fresco, dar sombra y agua; la miel es clara, aromática y cristaliza fino.",
           "Lawenda kwitnie od połowy czerwca do końca lipca, zależnie od wysokości. Przewoź nocą, w chłodzie, zapewnij cień i wodę, a spodziewaj się jasnego, aromatycznego miodu, który drobno krystalizuje."),
        honey="lavender",
    ),
    Entry(
        "harvest-linden", "harvest", "07-08", "07-31",
        _t("Linden honey: extract when ripe",
           "Lindenhonig: reif schleudern",
           "Miel de tilleul : extraire à maturité",
           "Miel de tilo: extraer cuando madure",
           "Miód lipowy: odwiruj, gdy dojrzeje"),
        _t("Linden honey is light and minty and sets slowly. Harvest when the combs are capped to two thirds and the water content is 18 % or less (refractometer). Extract in the warmth of the day and keep it apart from honeydew honey.",
           "Lindenhonig ist hell und minzig und kristallisiert langsam. Ernten, wenn die Waben zu zwei Dritteln verdeckelt sind und der Wassergehalt höchstens 18 % beträgt (Refraktometer). In der Wärme des Tages schleudern und von Honigtauhonig getrennt halten.",
           "Le miel de tilleul est clair et mentholé et cristallise lentement. Récolter quand les rayons sont operculés aux deux tiers et que la teneur en eau est de 18 % ou moins (réfractomètre). Extraire dans la chaleur du jour et le garder séparé du miel de miellat.",
           "La miel de tilo es clara y mentolada y cristaliza despacio. Cosechar cuando los panales estén operculados a dos tercios y el contenido de agua sea del 18 % o menos (refractómetro). Extraer con el calor del día y mantenerla separada de la miel de mielada.",
           "Miód lipowy jest jasny, miętowy i krystalizuje powoli. Zbieraj, gdy plastry są zasklepione w dwóch trzecich, a zawartość wody wynosi 18 % lub mniej (refraktometr). Wiruj w cieple dnia i trzymaj osobno od miodu spadziowego."),
        honey="linden",
    ),
    Entry(
        "migrate-sunflower", "migration", "07-01", "08-15",
        _t("Sunflower: a late flow",
           "Sonnenblume: eine späte Tracht",
           "Tournesol : une miellée tardive",
           "Girasol: una floración tardía",
           "Słonecznik: późny pożytek"),
        _t("Sunflower fields bloom in July and August. The pollen is rich and the honey sets very fast, so extract early. Ask about the seed treatment and spraying before you move.",
           "Sonnenblumenfelder blühen im Juli und August. Der Pollen ist reich und der Honig kristallisiert sehr schnell, deshalb früh schleudern. Vor dem Wandern nach Beizung und Spritzungen fragen.",
           "Les champs de tournesol fleurissent en juillet et août. Le pollen est riche et le miel cristallise très vite, donc extraire tôt. Se renseigner sur l’enrobage des semences et les traitements avant de déplacer.",
           "Los campos de girasol florecen en julio y agosto. El polen es rico y la miel cristaliza muy rápido, así que hay que extraer pronto. Preguntar por el tratamiento de las semillas y las fumigaciones antes de trasladar.",
           "Pola słonecznika kwitną w lipcu i sierpniu. Pyłek jest bogaty, a miód krystalizuje bardzo szybko, więc miodobranie rób wcześnie. Przed przewozem zapytaj o zaprawianie nasion i opryski."),
        honey="sunflower",
    ),
    Entry(
        "harvest-forest", "harvest", "07-15", "08-31",
        _t("Forest honey: extract in time, warm",
           "Waldhonig: rechtzeitig und warm schleudern",
           "Miel de forêt : extraire à temps, tiède",
           "Miel de bosque: extraer a tiempo y templada",
           "Miód leśny: odwiruj na czas, w cieple"),
        _t("Honeydew honey is thick. Warm the combs (a warm room) before extracting, and do not wait too long: with melezitose it turns to cement in the comb and cannot be extracted. Check the water content; honeydew honey keeps well at 18 % or less.",
           "Honigtauhonig ist zähflüssig. Die Waben vor dem Schleudern anwärmen (warmer Raum) und nicht zu lange warten: Mit Melezitose wird er in der Wabe steinhart und lässt sich nicht mehr schleudern. Wassergehalt prüfen; Honigtauhonig hält sich bei höchstens 18 % gut.",
           "Le miel de miellat est épais. Réchauffer les rayons (pièce chaude) avant d’extraire et ne pas attendre trop : avec du mélézitose, il durcit comme du ciment dans le rayon et ne s’extrait plus. Contrôler la teneur en eau ; le miel de miellat se conserve bien à 18 % ou moins.",
           "La miel de mielada es espesa. Calentar los panales (sala cálida) antes de extraer y no esperar demasiado: con melecitosa se vuelve cemento en el panal y ya no se extrae. Comprobar el contenido de agua; la miel de mielada se conserva bien con un 18 % o menos.",
           "Miód spadziowy jest gęsty. Przed wirowaniem ogrzej plastry (ciepłe pomieszczenie) i nie czekaj zbyt długo: z melecytozą zamienia się w plastrach w cement i nie da się go odwirować. Sprawdź zawartość wody; miód spadziowy dobrze się przechowuje przy 18 % lub mniej."),
        honey="fir",
    ),
    # ── Late summer and autumn ────────────────────────────────────────────────────────────
    Entry(
        "final-harvest", "harvest", "07-20", "08-10",
        _t("Last honey harvest of the season",
           "Letzte Honigernte der Saison",
           "Dernière récolte de miel de la saison",
           "Última cosecha de miel de la temporada",
           "Ostatnie miodobranie sezonu"),
        _t("Take off the last supers once the combs are capped and the water content is 18 % or less; a shake test and a refractometer tell you. Then treat against varroa and start feeding straight away: the winter bees are raised now, and they decide how the colony winters.",
           "Die letzten Honigräume abnehmen, sobald die Waben verdeckelt sind und der Wassergehalt höchstens 18 % beträgt; Schüttelprobe und Refraktometer zeigen es. Danach sofort gegen Varroa behandeln und mit der Fütterung beginnen: Jetzt entstehen die Winterbienen, und sie entscheiden, wie das Volk überwintert.",
           "Retirer les dernières hausses quand les rayons sont operculés et que la teneur en eau est de 18 % ou moins ; le test de secouage et le réfractomètre le disent. Traiter ensuite contre le varroa et commencer le nourrissement aussitôt : les abeilles d’hiver naissent maintenant, et elles décident de l’hivernage.",
           "Quitar las últimas alzas cuando los panales estén operculados y el agua sea del 18 % o menos; la prueba de sacudida y el refractómetro lo dicen. Después tratar contra la varroa y empezar a alimentar enseguida: ahora nacen las abejas de invierno y de ellas depende la invernada.",
           "Zdejmij ostatnie nadstawki, gdy plastry są zasklepione, a zawartość wody wynosi 18 % lub mniej; powie ci to próba strząsania i refraktometr. Potem od razu zrób zabieg przeciwko warrozie i zacznij karmić: wychowują się teraz pszczoły zimowe, a one decydują o tym, jak rodzina przezimuje."),
    ),
    Entry(
        "varroa-summer", "varroa", "07-25", "09-10",
        _t("Summer varroa treatment",
           "Sommerbehandlung gegen Varroa",
           "Traitement d’été contre le varroa",
           "Tratamiento de verano contra la varroa",
           "Letni zabieg przeciwko warrozie"),
        _t("Treat right after the last harvest, when the mites would otherwise damage the winter bees: long-term formic acid evaporators or another approved method, following the label and the temperature range. Check the effect with the debris on the bottom board. Medicines only as approved and prescribed in your country.",
           "Gleich nach der letzten Ernte behandeln, denn sonst schädigen die Milben die Winterbienen: Ameisensäure-Langzeitverdunster oder eine andere zugelassene Methode, nach Packungsbeilage und im vorgesehenen Temperaturbereich. Die Wirkung am Gemüll der Bodenfläche prüfen. Arzneimittel nur wie in deinem Land zugelassen und vorgeschrieben.",
           "Traiter juste après la dernière récolte, sinon les varroas abîment les abeilles d’hiver : diffuseurs d’acide formique à action prolongée ou autre méthode autorisée, selon la notice et la plage de température. Vérifier l’effet avec les débris sur le plateau. Médicaments uniquement selon l’autorisation et les règles de votre pays.",
           "Tratar justo después de la última cosecha, porque si no los ácaros dañan a las abejas de invierno: evaporadores de ácido fórmico de larga duración u otro método autorizado, según el prospecto y el rango de temperatura. Comprobar el efecto con los restos del fondo. Medicamentos solo según la autorización y las normas de tu país.",
           "Zabieg wykonaj tuż po ostatnim miodobraniu, zanim roztocza zaszkodzą pszczołom zimowym: długodziałające parowniki z kwasem mrówkowym albo inna dopuszczona metoda, zgodnie z ulotką i zakresem temperatur. Skuteczność sprawdź po osypie na dennicy. Leki tylko takie, jakie są dopuszczone i zalecone w twoim kraju."),
    ),
    Entry(
        "migrate-heather", "migration", "08-01", "09-10",
        _t("Heather: move to the moors",
           "Heide: in die Heidegebiete wandern",
           "Bruyère : emmener les ruches dans les landes",
           "Brezo: trasladar a los brezales",
           "Wrzos: przewieź na wrzosowiska"),
        _t("Heather (ling) blooms from August to early September. Move strong colonies after the summer treatment, with room above the brood. The weather decides the yield; the honey is dark, aromatic and jelly-like.",
           "Die Heide (Besenheide) blüht von August bis Anfang September. Starke Völker nach der Sommerbehandlung wandern, mit Platz über dem Brutraum. Das Wetter entscheidet über den Ertrag; der Honig ist dunkel, aromatisch und gelartig.",
           "La bruyère callune fleurit d’août à début septembre. Déplacer des colonies fortes après le traitement d’été, avec de la place au-dessus du couvain. La météo décide de la récolte ; le miel est foncé, aromatique et gélifié.",
           "El brezo (calluna) florece de agosto a principios de septiembre. Trasladar colonias fuertes después del tratamiento de verano, con espacio sobre la cría. El tiempo decide la cosecha; la miel es oscura, aromática y gelatinosa.",
           "Wrzos (wrzos zwyczajny) kwitnie od sierpnia do początku września. Silne rodziny przewoź po letnim zabiegu, z miejscem nad czerwiem. O plonie decyduje pogoda; miód jest ciemny, aromatyczny i galaretowaty."),
        honey="heather",
    ),
    Entry(
        "winter-feeding", "feeding", "08-01", "09-25",
        _t("Feed for the winter",
           "Einfüttern für den Winter",
           "Nourrir pour l’hiver",
           "Alimentar para el invierno",
           "Karm na zimę"),
        _t("Feed sugar syrup (3 parts sugar to 2 parts water) or ready-made feed, in a few large rations rather than many small ones, while it is still warm. A colony needs roughly 15–20 kg of stores, more in large hives. Feed in the evening and keep spills away from the hive.",
           "Zuckerlösung (3 Teile Zucker auf 2 Teile Wasser) oder Fertigfutter füttern, in wenigen großen Gaben statt vielen kleinen, solange es noch warm ist. Ein Volk braucht etwa 15–20 kg Vorrat, in großen Beuten mehr. Abends füttern und Verschüttetes von der Beute fernhalten.",
           "Donner du sirop de sucre (3 parts de sucre pour 2 parts d’eau) ou un aliment prêt à l’emploi, en quelques grosses distributions plutôt qu’en beaucoup de petites, tant qu’il fait encore chaud. Une colonie a besoin d’environ 15 à 20 kg de réserves, plus dans les grandes ruches. Nourrir le soir et éloigner ce qui est renversé.",
           "Dar jarabe de azúcar (3 partes de azúcar por 2 de agua) o alimento preparado, en pocas raciones grandes en lugar de muchas pequeñas, mientras haga calor. Una colonia necesita unos 15–20 kg de reservas, más en colmenas grandes. Alimentar por la tarde y mantener lejos lo derramado.",
           "Podawaj syrop cukrowy (3 części cukru na 2 części wody) lub gotowy pokarm, w kilku dużych porcjach zamiast wielu małych, póki jest jeszcze ciepło. Rodzina potrzebuje około 15–20 kg zapasów, w dużych ulach więcej. Karm wieczorem i nie zostawiaj rozlanego pokarmu przy ulu."),
    ),
    Entry(
        "robbing-wasps", "care", "08-01", "09-30",
        _t("Robbing and wasps",
           "Räuberei und Wespen",
           "Pillage et guêpes",
           "Pillaje y avispas",
           "Rabunek i osy"),
        _t("In the dearth after the flow bees and wasps rob weak colonies. Narrow the entrances, do not leave honey, wax or syrup around, open hives only briefly and in the evening, and unite weak colonies.",
           "In der Trachtlücke nach der Tracht plündern Bienen und Wespen schwache Völker. Fluglöcher verengen, keinen Honig, kein Wachs und keinen Sirup herumstehen lassen, Beuten nur kurz und abends öffnen und schwache Völker vereinigen.",
           "Dans la période creuse après la miellée, abeilles et guêpes pillent les colonies faibles. Réduire les entrées, ne laisser traîner ni miel, ni cire, ni sirop, n’ouvrir les ruches que brièvement et le soir, et réunir les colonies faibles.",
           "En la escasez tras la floración, abejas y avispas pillan las colonias débiles. Reducir las piqueras, no dejar miel, cera ni jarabe por ahí, abrir las colmenas solo brevemente y por la tarde, y unir las colonias débiles.",
           "W bezpożytku po sezonie pszczoły i osy rabują słabe rodziny. Zwęź wyloty, nie zostawiaj miodu, wosku ani syropu, otwieraj ule tylko na krótko i wieczorem, a słabe rodziny połącz."),
    ),
    Entry(
        "harvest-heather", "harvest", "09-05", "09-30",
        _t("Heather honey: press, do not extract",
           "Heidehonig: pressen, nicht schleudern",
           "Miel de bruyère : presser, pas extraire",
           "Miel de brezo: prensar, no extraer",
           "Miód wrzosowy: wyciśnij, nie odwirowuj"),
        _t("Heather honey is thixotropic: it is jelly-like at rest and cannot be spun out. Loosen it with a pin roller or press the combs. Harvest when it is ripe and the combs are capped; do not stir it more than needed.",
           "Heidehonig ist thixotrop: In Ruhe ist er gelartig und lässt sich nicht schleudern. Mit einer Stachelwalze lockern oder die Waben pressen. Ernten, wenn er reif und die Waben verdeckelt sind; nicht mehr rühren als nötig.",
           "Le miel de bruyère est thixotrope : gélifié au repos, il ne s’extrait pas par centrifugation. L’ameublir avec un rouleau à pointes ou presser les rayons. Récolter à maturité, rayons operculés ; ne pas le remuer plus que nécessaire.",
           "La miel de brezo es tixotrópica: en reposo es gelatinosa y no se puede centrifugar. Aflojarla con un rodillo de púas o prensar los panales. Cosechar cuando esté madura y los panales operculados; no removerla más de lo necesario.",
           "Miód wrzosowy jest tiksotropowy: w spoczynku jest galaretowaty i nie da się go odwirować. Rozluźnij go szczotką z igłami albo wyciśnij plastry. Zbieraj, gdy jest dojrzały, a plastry zasklepione; nie mieszaj go więcej niż trzeba."),
        honey="heather",
    ),
    Entry(
        "ivy-bloom", "bloom", "09-10", "10-20",
        _t("Ivy: the last flow",
           "Efeu: die letzte Tracht",
           "Lierre : la dernière miellée",
           "Hiedra: la última floración",
           "Bluszcz: ostatni pożytek"),
        _t("Ivy blooms late and feeds the winter bees with pollen and nectar. Its honey sets extremely fast, so do not leave it in supers: it belongs to the bees. Make sure no honey from ivy is left in combs you want to extract.",
           "Der Efeu blüht spät und versorgt die Winterbienen mit Pollen und Nektar. Sein Honig kristallisiert extrem schnell, deshalb nicht in Honigräumen lassen: Er gehört den Bienen. Darauf achten, dass kein Efeuhonig in Waben bleibt, die geschleudert werden sollen.",
           "Le lierre fleurit tard et nourrit les abeilles d’hiver en pollen et nectar. Son miel cristallise extrêmement vite, il ne faut donc pas le laisser dans les hausses : il appartient aux abeilles. Veiller à ce qu’aucun miel de lierre ne reste dans des rayons à extraire.",
           "La hiedra florece tarde y alimenta a las abejas de invierno con polen y néctar. Su miel cristaliza muy rápido, así que no hay que dejarla en las alzas: es de las abejas. Cuidar que no quede miel de hiedra en panales que se vayan a extraer.",
           "Bluszcz kwitnie późno i żywi pszczoły zimowe pyłkiem i nektarem. Jego miód krystalizuje wyjątkowo szybko, więc nie zostawiaj go w nadstawkach: należy do pszczół. Dopilnuj, żeby w plastrach, które chcesz odwirować, nie został miód z bluszczu."),
    ),
    Entry(
        "winter-check", "inspection", "09-01", "09-30",
        _t("Check the colonies before winter",
           "Völker vor dem Winter prüfen",
           "Contrôler les colonies avant l’hiver",
           "Revisar las colonias antes del invierno",
           "Sprawdź rodziny przed zimą"),
        _t("Make sure each colony has a queen, enough bees (about six or more frames) and enough stores. Unite weak colonies or give up hopeless ones: they would not survive and would draw robbers. Remove the supers and reduce the space to what the colony can keep warm.",
           "Prüfen, dass jedes Volk eine Königin, genug Bienen (etwa sechs oder mehr Wabengassen) und genug Vorrat hat. Schwache Völker vereinigen oder aussichtslose aufgeben: Sie überleben nicht und locken Räuber an. Honigräume abnehmen und den Raum auf das verkleinern, was das Volk warmhalten kann.",
           "S’assurer que chaque colonie a une reine, assez d’abeilles (environ six cadres ou plus) et assez de provisions. Réunir les colonies faibles ou renoncer aux sans-espoir : elles ne survivraient pas et attireraient les pillards. Retirer les hausses et réduire l’espace à ce que la colonie peut garder au chaud.",
           "Comprobar que cada colonia tiene reina, suficientes abejas (unos seis cuadros o más) y suficientes reservas. Unir las colonias débiles o dar por perdidas las que no tienen remedio: no sobrevivirían y atraerían pilladoras. Quitar las alzas y reducir el espacio a lo que la colonia puede mantener caliente.",
           "Upewnij się, że każda rodzina ma matkę, dość pszczół (około sześciu ramek lub więcej) i dość zapasów. Słabe rodziny połącz lub zrezygnuj z beznadziejnych: nie przezimują i przyciągną rabusiów. Zdejmij nadstawki i zmniejsz przestrzeń do tej, którą rodzina potrafi ogrzać."),
    ),
    Entry(
        "winter-prep", "winter", "10-01", "11-20",
        _t("Make the hives winter-proof",
           "Beuten winterfest machen",
           "Préparer les ruches pour l’hiver",
           "Preparar las colmenas para el invierno",
           "Przygotuj ule do zimy"),
        _t("Fit the mouse guard and a reduced entrance, make sure the hive stands firm and slightly tilted forward, and keep it ventilated (open mesh floor or ventilation). Protect against wind and woodpeckers. After this, the colonies are left in peace.",
           "Mäusegitter und ein verkleinertes Flugloch anbringen, die Beute standfest und leicht nach vorn geneigt aufstellen und für Belüftung sorgen (offener Gitterboden oder Lüftung). Vor Wind und Spechten schützen. Danach bleiben die Völker in Ruhe.",
           "Poser la grille anti-souris et une entrée réduite, s’assurer que la ruche est stable et légèrement inclinée vers l’avant, et la ventiler (plancher grillagé ouvert ou aération). Protéger du vent et des pics. Ensuite, les colonies sont laissées en paix.",
           "Poner la rejilla contra ratones y una piquera reducida, asegurar que la colmena esté firme y algo inclinada hacia delante, y mantenerla ventilada (fondo de rejilla abierto o ventilación). Proteger del viento y de los pájaros carpinteros. Después, las colonias se dejan en paz.",
           "Załóż zabezpieczenie przed myszami i zmniejszony wylot, dopilnuj, by ul stał stabilnie i lekko pochylony do przodu, i zadbaj o wentylację (dennica siatkowa lub wentylacja). Zabezpiecz przed wiatrem i dzięciołami. Potem rodziny zostają w spokoju."),
    ),
    Entry(
        "foulbrood-sample", "care", "09-15", "10-31",
        _t("Feed ring sample for foulbrood",
           "Futterkranzprobe auf Faulbrut",
           "Prélèvement de couronne de miel pour la loque",
           "Muestra de miel de la corona para la loque",
           "Próbka pokarmu na zgnilca"),
        _t("Where the authorities require or recommend it, take a sample of the feed ring (the honey at the edge of the brood nest) of each apiary in autumn and send it to the lab. A positive result must be reported and treated by the rules.",
           "Wo die Behörde es vorschreibt oder empfiehlt, im Herbst von jedem Stand eine Futterkranzprobe (Honig am Rand des Brutnests) nehmen und ins Labor schicken. Ein positives Ergebnis muss gemeldet und nach den Vorschriften behandelt werden.",
           "Là où l’autorité l’exige ou le recommande, prélever à l’automne un échantillon de la couronne de miel (le miel en bordure du nid à couvain) de chaque rucher et l’envoyer au laboratoire. Un résultat positif doit être déclaré et traité selon les règles.",
           "Donde la autoridad lo exija o recomiende, tomar en otoño una muestra de la corona de miel (la miel del borde del nido de cría) de cada colmenar y enviarla al laboratorio. Un resultado positivo debe comunicarse y tratarse según las normas.",
           "Tam, gdzie władze tego wymagają lub zalecają, pobierz jesienią próbkę pokarmu (miód na skraju gniazda czerwiowego) z każdej pasieki i wyślij do laboratorium. Wynik dodatni trzeba zgłosić i zwalczać według przepisów."),
    ),
    Entry(
        "oxalic-acid", "varroa", "11-25", "12-31",
        _t("Winter treatment with oxalic acid in the brood-free time",
           "Winterbehandlung mit Oxalsäure in der brutfreien Zeit",
           "Traitement d’hiver à l’acide oxalique hors couvain",
           "Tratamiento de invierno con ácido oxálico sin cría",
           "Zabieg zimowy kwasem szczawiowym w okresie bez czerwiu"),
        _t("After some days of hard frost the colonies are almost free of brood, and the mites sit on the bees. Trickle or spray oxalic acid then, once, as approved and exactly by the instructions; wear protective gear. Check the debris afterwards.",
           "Nach einigen Tagen mit Dauerfrost sind die Völker fast brutfrei, und die Milben sitzen auf den Bienen. Dann einmal Oxalsäure träufeln oder sprühen, wie zugelassen und genau nach Anleitung; Schutzausrüstung tragen. Danach das Gemüll prüfen.",
           "Après quelques jours de gel durable, les colonies sont presque sans couvain et les varroas sont sur les abeilles. Appliquer alors une fois de l’acide oxalique par dégouttement ou pulvérisation, selon l’autorisation et exactement selon la notice ; porter un équipement de protection. Contrôler ensuite les débris.",
           "Tras unos días de helada continua, las colonias están casi sin cría y los ácaros están sobre las abejas. Entonces aplicar una vez ácido oxálico por goteo o pulverización, como esté autorizado y exactamente según las instrucciones; usar protección. Después revisar los restos del fondo.",
           "Po kilku dniach silnego mrozu rodziny prawie nie mają czerwiu, a roztocza siedzą na pszczołach. Wtedy raz zakrop lub opryskaj kwasem szczawiowym, zgodnie z dopuszczeniem i dokładnie według instrukcji; używaj sprzętu ochronnego. Potem sprawdź osyp."),
    ),
    Entry(
        "winter-work", "care", "11-20", "12-31",
        _t("Winter work: wax, equipment and planning",
           "Winterarbeit: Wachs, Geräte und Planung",
           "Travaux d’hiver : cire, matériel et planification",
           "Trabajo de invierno: cera, material y planificación",
           "Prace zimowe: wosk, sprzęt i planowanie"),
        _t("Melt old combs, clean and store the supers and frames, repair and paint hives and look at the stock records: which colonies were strong, which swarmed, what was the yield? Plan the next season, order foundation and treatments.",
           "Alte Waben einschmelzen, Honigräume und Rähmchen reinigen und lagern, Beuten reparieren und streichen und die Stockkarten ansehen: Welche Völker waren stark, welche haben geschwärmt, wie war der Ertrag? Die nächste Saison planen, Mittelwände und Mittel bestellen.",
           "Fondre les vieux rayons, nettoyer et ranger les hausses et les cadres, réparer et peindre les ruches et relire les fiches de ruche : quelles colonies étaient fortes, lesquelles ont essaimé, quel a été le rendement ? Planifier la saison suivante, commander cire gaufrée et traitements.",
           "Fundir los panales viejos, limpiar y guardar las alzas y los cuadros, reparar y pintar las colmenas y mirar las fichas: ¿qué colonias fueron fuertes, cuáles enjambraron, cuál fue el rendimiento? Planificar la próxima temporada, encargar cera estampada y tratamientos.",
           "Wytop stare plastry, wyczyść i schowaj nadstawki i ramki, napraw i pomaluj ule oraz przejrzyj dokumentację pasieki: które rodziny były silne, które się rójkowały, jaki był plon? Zaplanuj następny sezon, zamów węzę i preparaty."),
    ),
)


def entry_by_key(key: str) -> Optional[Entry]:
    return next((e for e in ENTRIES if e.key == key), None)
